package com.bao.doan.entity;
// Generated Mar 22, 2020 8:59:51 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ApplicationCounter generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "application_counter", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "tablename"))
public class ApplicationCounter implements java.io.Serializable {

	private long id;
	private String tablename;
	private Long currentid;
	private Date currentime;

	public ApplicationCounter() {
	}

	public ApplicationCounter(long id) {
		this.id = id;
	}

	public ApplicationCounter(long id, String tablename, Long currentid, Date currentime) {
		this.id = id;
		this.tablename = tablename;
		this.currentid = currentid;
		this.currentime = currentime;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "tablename", unique = true)
	public String getTablename() {
		return this.tablename;
	}

	public void setTablename(String tablename) {
		this.tablename = tablename;
	}

	@Column(name = "currentid")
	public Long getCurrentid() {
		return this.currentid;
	}

	public void setCurrentid(Long currentid) {
		this.currentid = currentid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "currentime", length = 29)
	public Date getCurrentime() {
		return this.currentime;
	}

	public void setCurrentime(Date currentime) {
		this.currentime = currentime;
	}

}
