package com.bao.doan.entity;
// Generated Mar 29, 2020 8:15:32 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "category", schema = "public")
public class Category implements java.io.Serializable {

	private long id;
	private String name;
	private short daxoa;
	private String token;

	public Category() {
	}

	public Category(long id, short daxoa) {
		this.id = id;
		this.daxoa = daxoa;
	}

	public Category(long id, String name, short daxoa, String token) {
		this.id = id;
		this.name = name;
		this.daxoa = daxoa;
		this.token = token;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "daxoa", nullable = false)
	public short getDaxoa() {
		return this.daxoa;
	}

	public void setDaxoa(short daxoa) {
		this.daxoa = daxoa;
	}
	
	@Column(name = "token")
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
