package com.bao.doan.entity;
// Generated Mar 29, 2020 8:15:32 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Movie generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "movie", schema = "public")
public class Movie implements java.io.Serializable {

	private long id;
	private String codemovie;
	private String title;
	private Long year;
	private double rating;
	private String ratingvotes;
	private String trailer;
	private String poster;
	private String plot;
	private String caster;
	private String linkfilm;
	private short daxoa;
	private long numview;
	private long cid;
	private String token;

	public Movie() {
	}

	public Movie(long id, String title, long rating, String poster, short daxoa, long numview, long cid) {
		this.id = id;
		this.title = title;
		this.rating = rating;
		this.poster = poster;
		this.daxoa = daxoa;
		this.numview = numview;
		this.cid = cid;
	}

	public Movie(long id, String codemovie, String title, Long year, double rating, String ratingvotes, String trailer, String poster,
			String plot, String caster, String linkfilm, short daxoa, long numview ,long cid, String token) {
		this.id = id;
		this.codemovie = codemovie;
		this.title = title;
		this.year = year;
		this.rating = rating;
		this.ratingvotes = ratingvotes;
		this.trailer = trailer;
		this.poster = poster;
		this.plot = plot;
		this.caster = caster;
		this.linkfilm = linkfilm;
		this.daxoa = daxoa;
		this.numview = numview;
		this.cid = cid;
		this.token = token;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}
	
	@Column(name = "codemovie", nullable = false)
	public String getCodemovie() {
		return this.codemovie;
	}

	public void setCodemovie(String codemovie) {
		this.codemovie = codemovie;
	}

	@Column(name = "title", nullable = false)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "year")
	public Long getYear() {
		return this.year;
	}

	public void setYear(Long year) {
		this.year = year;
	}

	@Column(name = "rating", nullable = false)
	public double getRating() {
		return this.rating;
	}

	public void setRating(double d) {
		this.rating = d;
	}

	@Column(name = "ratingvotes")
	public String getRatingvotes() {
		return this.ratingvotes;
	}

	public void setRatingvotes(String ratingvotes) {
		this.ratingvotes = ratingvotes;
	}

	@Column(name = "trailer")
	public String getTrailer() {
		return this.trailer;
	}

	public void setTrailer(String trailer) {
		this.trailer = trailer;
	}

	@Column(name = "poster", nullable = false, length = 100)
	public String getPoster() {
		return this.poster;
	}

	public void setPoster(String poster) {
		this.poster = poster;
	}

	@Column(name = "plot")
	public String getPlot() {
		return this.plot;
	}

	public void setPlot(String plot) {
		this.plot = plot;
	}

	@Column(name = "caster", length = 100)
	public String getCaster() {
		return this.caster;
	}

	public void setCaster(String caster) {
		this.caster = caster;
	}

	@Column(name = "linkfilm", length = 100)
	public String getLinkfilm() {
		return this.linkfilm;
	}

	public void setLinkfilm(String linkfilm) {
		this.linkfilm = linkfilm;
	}

	@Column(name = "daxoa", nullable = false)
	public short getDaxoa() {
		return this.daxoa;
	}

	public void setDaxoa(short daxoa) {
		this.daxoa = daxoa;
	}
	
	@Column(name = "numview", unique = true, nullable = false)
	public long getNumview() {
		return this.numview;
	}

	public void setNumview(long numview) {
		this.numview = numview;
	}

	@Column(name = "token")
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}
	
	@Column(name = "cid", unique = true, nullable = false)
	public long getCid() {
		return this.cid;
	}

	public void setCid(long cid) {
		this.cid = cid;
	}

}
