package com.bao.doan.entity;
// Generated Mar 29, 2020 8:15:32 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MovieRating generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "movie_rating", schema = "public")
public class MovieRating implements java.io.Serializable {

	private long id;
	private long movieid;
	private Long userid;
	private double rating;
	private short daxoa;
	private String token;

	public MovieRating() {
	}

	public MovieRating(long id, long movieid, double rating, short daxoa, String token) {
		this.id = id;
		this.movieid = movieid;
		this.rating = rating;
		this.daxoa = daxoa;
		this.token = token;
	}

	public MovieRating(long id, long movieid, Long userid, double rating, short daxoa, String token) {
		this.id = id;
		this.movieid = movieid;
		this.userid = userid;
		this.rating = rating;
		this.daxoa = daxoa;
		this.token = token;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "movieid", nullable = false)
	public long getMovieid() {
		return this.movieid;
	}

	public void setMovieid(long movieid) {
		this.movieid = movieid;
	}

	@Column(name = "userid")
	public Long getUserid() {
		return this.userid;
	}

	public void setUserid(Long userid) {
		this.userid = userid;
	}

	@Column(name = "rating", nullable = false)
	public double getRating() {
		return this.rating;
	}

	public void setRating(double rating) {
		this.rating = rating;
	}

	@Column(name = "daxoa", nullable = false)
	public short getDaxoa() {
		return this.daxoa;
	}

	public void setDaxoa(short daxoa) {
		this.daxoa = daxoa;
	}
	
	@Column(name = "token", nullable = false)
	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}
	
	

}
