package com.bao.doan.entity;
// Generated Mar 22, 2020 8:59:51 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Nguoidung generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "nguoidung", schema = "public", uniqueConstraints = { @UniqueConstraint(columnNames = "email"),
		@UniqueConstraint(columnNames = "tendangnhap") })
public class Nguoidung implements java.io.Serializable {

	private long id;
	private String tendangnhap;
	private String email;
	private Short kichhoat;
	private String hoten;
	private Date ngaytao;
	private String nguoitao;
	private Date ngaysua;
	private String nguoisua;
	private short daxoa;
	private String vaitro;
	private String token;

	public Nguoidung() {
	}

	public Nguoidung(long id, String tendangnhap, String email, String hoten, Date ngaytao, String nguoitao,
			short daxoa) {
		this.id = id;
		this.tendangnhap = tendangnhap;
		this.email = email;
		this.hoten = hoten;
		this.ngaytao = ngaytao;
		this.nguoitao = nguoitao;
		this.daxoa = daxoa;
	}

	public Nguoidung(long id, String tendangnhap, String email, Short kichhoat, String hoten, Date ngaytao,
			String nguoitao, Date ngaysua, String nguoisua, short daxoa, String vaitro, String token) {
		this.id = id;
		this.tendangnhap = tendangnhap;
		this.email = email;
		this.kichhoat = kichhoat;
		this.hoten = hoten;
		this.ngaytao = ngaytao;
		this.nguoitao = nguoitao;
		this.ngaysua = ngaysua;
		this.nguoisua = nguoisua;
		this.daxoa = daxoa;
		this.vaitro = vaitro;
		this.token = token;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "tendangnhap", unique = true, nullable = false, length = 100)
	public String getTendangnhap() {
		return this.tendangnhap;
	}

	public void setTendangnhap(String tendangnhap) {
		this.tendangnhap = tendangnhap;
	}

	@Column(name = "email", unique = true, nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "kichhoat")
	public Short getKichhoat() {
		return this.kichhoat;
	}

	public void setKichhoat(Short kichhoat) {
		this.kichhoat = kichhoat;
	}

	@Column(name = "hoten", nullable = false)
	public String getHoten() {
		return this.hoten;
	}

	public void setHoten(String hoten) {
		this.hoten = hoten;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngaytao", nullable = false, length = 29)
	public Date getNgaytao() {
		return this.ngaytao;
	}

	public void setNgaytao(Date ngaytao) {
		this.ngaytao = ngaytao;
	}

	@Column(name = "nguoitao", nullable = false, length = 100)
	public String getNguoitao() {
		return this.nguoitao;
	}

	public void setNguoitao(String nguoitao) {
		this.nguoitao = nguoitao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngaysua", length = 29)
	public Date getNgaysua() {
		return this.ngaysua;
	}

	public void setNgaysua(Date ngaysua) {
		this.ngaysua = ngaysua;
	}

	@Column(name = "nguoisua", length = 100)
	public String getNguoisua() {
		return this.nguoisua;
	}

	public void setNguoisua(String nguoisua) {
		this.nguoisua = nguoisua;
	}

	@Column(name = "daxoa", nullable = false)
	public short getDaxoa() {
		return this.daxoa;
	}

	public void setDaxoa(short daxoa) {
		this.daxoa = daxoa;
	}

	@Column(name = "vaitro", length = 20)
	public String getVaitro() {
		return this.vaitro;
	}

	public void setVaitro(String vaitro) {
		this.vaitro = vaitro;
	}

	@Column(name = "token", length = 32)
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
