package com.bao.doan.entity;
// Generated Jun 6, 2020 11:04:50 AM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Numberview generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "numberview", schema = "public")
public class Numberview implements java.io.Serializable {

	private long id;
	private long movieid;
	private long numberview;
	private Date ngaybatdau;
	private Date ngaycapnhat;
	private short daxoa;
	private String token;

	public Numberview() {
	}

	public Numberview(long id, long movieid, long numberview, short daxoa) {
		this.id = id;
		this.movieid = movieid;
		this.numberview = numberview;
		this.daxoa = daxoa;
	}

	public Numberview(long id, long movieid, long numberview, Date ngaybatdau, Date ngaycapnhat, short daxoa,
			String token) {
		this.id = id;
		this.movieid = movieid;
		this.numberview = numberview;
		this.ngaybatdau = ngaybatdau;
		this.ngaycapnhat = ngaycapnhat;
		this.daxoa = daxoa;
		this.token = token;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "movieid", nullable = false)
	public long getMovieid() {
		return this.movieid;
	}

	public void setMovieid(long movieid) {
		this.movieid = movieid;
	}

	@Column(name = "numberview", nullable = false)
	public long getNumberview() {
		return this.numberview;
	}

	public void setNumberview(long numberview) {
		this.numberview = numberview;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngaybatdau", length = 29)
	public Date getNgaybatdau() {
		return this.ngaybatdau;
	}

	public void setNgaybatdau(Date ngaybatdau) {
		this.ngaybatdau = ngaybatdau;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngaycapnhat", length = 29)
	public Date getNgaycapnhat() {
		return this.ngaycapnhat;
	}

	public void setNgaycapnhat(Date ngaycapnhat) {
		this.ngaycapnhat = ngaycapnhat;
	}

	@Column(name = "daxoa", nullable = false)
	public short getDaxoa() {
		return this.daxoa;
	}

	public void setDaxoa(short daxoa) {
		this.daxoa = daxoa;
	}

	@Column(name = "token")
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
