package com.bao.doan.entity;
// Generated May 18, 2020 8:38:13 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Payment generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "payment", schema = "public")
public class Payment implements java.io.Serializable {

	private long id;
	private String name;
	private double amount;
	private short daxoa;
	private String token;

	public Payment() {
	}

	public Payment(long id, String name, double amount, short daxoa) {
		this.id = id;
		this.name = name;
		this.amount = amount;
		this.daxoa = daxoa;
	}

	public Payment(long id, String name, double amount, short daxoa, String token) {
		this.id = id;
		this.name = name;
		this.amount = amount;
		this.daxoa = daxoa;
		this.token = token;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "amount", nullable = false, precision = 17, scale = 17)
	public double getAmount() {
		return this.amount;
	}

	public void setAmount(double amount) {
		this.amount = amount;
	}

	@Column(name = "daxoa", nullable = false)
	public short getDaxoa() {
		return this.daxoa;
	}

	public void setDaxoa(short daxoa) {
		this.daxoa = daxoa;
	}

	@Column(name = "token")
	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

}
